FROM node:22-alpine

# Install dependencies
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm i

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Run development server with hot reload
CMD ["pnpm", "dev"]
